<?php
//数据库主机
define('BX_DB_HOST','localhost');
//数据库用户名
define('BX_DB_USER','root');
//数据库密码
define('BX_DB_PASS','123456');
//数据库名字
define('BX_DB_NAME','baixiu');
//网站根目录,php自带的函数需写路径是用
define('ROOT_DIR',dirname(__FILE__));